name: deploy website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files to /var/www/html
        run: |
          cp -r *  /var/www/html
